spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    root: info
    rightagile.badge.stage: debug
    jdbc.sqlonly: debug
    org.springframework.web: debug
    com.zaxxer.hikari.HikariDataSource: error
